[versions]
junit = { strictly = '5.8.2' }
nva-commons = { strictly = '1.25.20' }
jackson = { require = '2.13.3' }
mockito = { strictly = '4.5.1' }
hamcrest = { strictly = '2.2' }
aws-lambda-java-core = { strictly = '1.2.1' }
aws-lambda-java-events = { strictly = '3.11.0' }
aws-lambda-java-log4j2 = { strictly = '1.5.1' }
log4j = { strictly = '2.17.2' }
log4jApi = { strictly = '2.17.2' }
slf4j = { require = '1.7.36' }
slf4j-impl = { strictly = '2.17.2' }
nva-language = { strictly = '1.0' }
awsSdk2 = { strictly = '2.17.191' }
wiremock = { strictly = '2.33.2' }
jaxb = { strictly = '4.0.2' }
gson = { strictly = '2.10.1' }
apache-commons = { strictly = '3.12.0' }

[libraries]

#Test

junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit' }

mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
hamcrest-core = { group = 'org.hamcrest', name = 'hamcrest-core', version.ref = 'hamcrest' }

nva-testutils = { group = 'com.github.bibsysdev', name = 'nvatestutils', version.ref = 'nva-commons' }
nva-logutils = { group = 'com.github.bibsysdev', name = 'logutils', version.ref = 'nva-commons' }

wiremock = { group = 'com.github.tomakehurst', name = 'wiremock-jre8', version.ref = 'wiremock' }

#Regular

nva-commons-core = { group = 'com.github.bibsysdev', name = 'core', version.ref = 'nva-commons' }
nva-s3 = { group = 'com.github.bibsysdev', name = 's3', version.ref = 'nva-commons' }
nva-language = { group = 'com.github.bibsysdev', name = 'nva-language', version.ref = 'nva-language' }

jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }

aws-lambda-java-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'aws-lambda-java-core' }
aws-lambda-java-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'aws-lambda-java-events' }
aws-lambda-java-log4j2 = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'aws-lambda-java-log4j2' }
aws-sdk2-secrets = { group = 'software.amazon.awssdk', name = 'secretsmanager', version.ref = 'awsSdk2' }
aws-sdk2-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'awsSdk2' }

log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4jApi' }
log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }
log4j-slf4j-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j18-impl', version.ref = 'slf4j-impl' }

jaxb-runtime = { group = 'org.glassfish.jaxb', name = 'jaxb-runtime', version.ref = 'jaxb' }

google-gson = { group = 'com.google.code.gson', name = 'gson', version.ref = 'gson' }

apache-commons-lang3 = { group = 'org.apache.commons', name = 'commons-lang3', version.ref = 'apache-commons' }
