name: Lint CloudFormation Templates

on: [ push ]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Run cfn-lint on template and pipeline
        run: |
          cfn-lint --version
          /bin/sh -c "cat pipeline.yml | sed '/CODEBUILD_RESOLVED_SOURCE_VERSION/d' | cfn-lint -"
          /bin/sh -c "cat template.yaml | sed '/CODEBUILD_RESOLVED_SOURCE_VERSION/d' | cfn-lint -"
          echo Linting Complete!
